import { Roboto } from "next/font/google";

import type { Metadata, Viewport } from "next";

import "./globals.css";
import { PokedexHeader } from "@/components/layout/Header";
import QueryProvider from "@/providers/QueryProvider";
import ThemeRegistry from "@/theme/ThemeProvider";


const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ['100', '200', '300', '400', '500', '700', '900'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} antialiased`}
      >
        <QueryProvider>
          <ThemeRegistry>
            <PokedexHeader />
            {children}
          </ThemeRegistry>
        </QueryProvider>
      </body>
    </html>
  );
}
